[env]

[target.armv7-linux-androideabi]
linker = "armv7a-linux-androideabi21-clang"

[target.aarch64-linux-android]
linker = "aarch64-linux-android21-clang"

[alias]

windows = "build --target x86_64-pc-windows-gnu"
android = "build --target aarch64-linux-android"